---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: Windows2012R2
  driver_config:
      box: mwrock/Windows2012R2
      username: vagrant
      password: vagrant
      communicator: winrm

suites:
  - name: default
    run_list:
      - recipe[windows_provisioning::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
