Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "mwrock/Windows2012R2"
  c.vm.communicator = "winrm"
    c.winrm.username = "vagrant"
    c.winrm.password = "vagrant"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
